### ISSUE TITLE
exact resolution

### ISSUE THREAD

**Issue by ghost** [sevensins/Wallbase-Downloader#10]
I changed setting to eqeq to get exact resolution. It seems to be getting everything at my set resolution and above. Aspect ration is correct. Also it is not grabbing any of the NSFW content. I have my login information entered. When the script starts it does not give me any errors

```
#################################
###   Configuration Options   ###
#################################

# For accepted values see Section 6
MAX_RANGE=160000
# For accepted values of resolution see Section 1
RESOLUTION=2560x1440
# For accepted values of aspect ratio see Section 2
ASPECTRATIO=1.77
# For accepted values of PURITY see Section 3
PURITY=111
# For accepted values of topic see Section 4
TOPIC=123
# For accepted values for SIZE see Section 5
SIZE=eqeq
# For accepted Thumbnails per page see Section 6
THPP=20
# For download location see Section 7
LOCATION=~/wallpapers
# Best of : see Section 8
TIME=1
# For Types see Section 9
TYPE=1
# For order Options see Section 10
ORDER=relevance
# See Section 11
ORDER_TYPE=desc
# See Section 12
QUERY="$1"
# See Section 14
COLLECTION=0
# See Section 15
CATEGORIZE=0
# See Section 16
WP_RANGE_START=0
WP_RANGE_STOP=0
```

**Comment by macearl** [comment]
Sorry for the delay, totally forgot about it.

I just tested the script with your settings and it works fine for me (almost)

The only thing i can reproduce is the resolution bug. I just tried it manually on wallbase.cc it seems the Aspectratio overrides the eqeq if you set aspectratio to 0 it should work (at least the first 100 random wallpapers i got were 2560x1440)

How did you enter your login information?

lets say your username is test and your password is 123

if you didnt enter it like this, try it this way.

```
# See Section 13
# Enter your Username
USER="test"
# Enter your password
PASS="123"
```

Also in the email i got, when you opened the issue it said something about an error in wgetrc, did you manage to resolve that one?

also you might want to reconsider your max_range value 160.000 seems a bit overkill. Currently wallbase should have around 3.033.XXX and thats all resolutions possible.

**Comment by ghost** [comment]
Thanks for the reply. I wanted to pull some wallpapers since the owner seems to be MIA for the last few months. Uploads are broken and the domain expires early next year. 

I will be sure to set aspect ratio to 0 to overcome pulling extra wallpapers. Thanks for figuring that one out. I will tone down max_range value. 

On the password part I had it entered correctly. The only thing I can think of is I have special characters in my password *#&!) for example. Could that cause it not to pull images that you need to be logged in for? I can change my password real fast and see if it makes any difference and report back. 

Also I got the wgetrc error fixed. I had a old setting in there to play nice with sorceforge that seems to be outdated now.

**Comment by ghost** [comment]
Just did a test. I am pulling exact resolutions now. Still no NSFW. 

```
##################################
###    Needed for NSFW/New     ###
##################################

# See Section 13
# Enter your Username
USER="username"
# Enter your password
PASS="password"

#################################
###  End needed for NSFW/New  ###
#################################
```

```
# For accepted values of PURITY see Section 3
PURITY=001
```

**Comment by macearl** [comment]
did you try removing special characters from your password?

even though i just changed my password to contain a few special characters (! ? # ') and nsfw still works.

You could also remove "do_login" from the last line and take a look at the file, if you open it with a browser it should display some sort of welcome message (or an error if the login does not work)

edit: tested some more special characters if you havent tried it already remove the & from your password, that should be the problem

**Comment by ghost** [comment]
I got it working. I first changed my password to remove special characters. I still wasn't pulling NSFW so I checked which version of wget I had. It was 1.12 so I downloaded 1.14, complied it and it is working perfect now. No idea why latest CentOS has old wget. 

Thanks for the help troubleshooting this macearl and for such a great script.
