### ISSUE TITLE
MIssing wget flag.

### ISSUE THREAD

**Issue by dominique120** [sevensins/Wallbase-Downloader#14]
On line 479 at the end there is a missing flag.

**Comment by macearl** [comment]
there is no missing flag, unless you mean something else than 

```
...$number -i - 
```

Here is the part from the wget manual:

```
You have a file that contains the URLs you want to download? Use the ‘-i’ switch:
wget -i file
If you specify ‘-’ as file name, the URLs will be read from standard input.
```

source: http://www.gnu.org/software/wget/manual/wget.html

**Comment by dominique120** [comment]
I did not know that.

Also, could we use something like axel/aria2 instead of wget to download stuff faster.

**Comment by macearl** [comment]
i would have to take a look at them, but im guessing it should not be a problem, the script downloads simple http links after all

edit:
it looks like aria2 does not support sending data via post, so its not possible to login using aria2
maybe its possible with a mix of aria2 and wget (wget for the login and aria2 for the rest, but aria doesnt seem to load the cookies.txt from wget) for simple download with aria (without the content for which you need to be logged in) just change all occurences of wget with aria2c and change all capital "-O" to lower case "-o" also remove the "--keep-session-cookies"

and axel does not seem to have the function to download links from a file or from standard input like with "-i -" also i dont see anything about cookies in the manpage
