### ISSUE TITLE
length: unspecified...

### ISSUE THREAD

**Issue by veepee78** [sevensins/Wallbase-Downloader#3]
Hi, thanks for awesome script!

Getting this error with the latest 2.6.2 version:

$ ./wallbase.sh
Cannot open cookies file `cookies.txt': No such file or directory
--2012-12-18 08:52:28--  http://wallbase.cc/toplist/0/23/gteq/0/0/100/60/0
Resolving wallbase.cc (wallbase.cc)... 46.105.105.101
Connecting to wallbase.cc (wallbase.cc)|46.105.105.101|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to:`0.3'

```
[  <=>                                  ] 92,009       290K/s   in 0.3s
```

2012-12-18 08:52:28 (290 KB/s) - `0.3' saved [92009]

File already downloaded!
File already downloaded!

I ran it for a while and got files 0, 0.1, 0.2 and 0.3 to the download directory. I had previously 2.6 and it worked fine.

**Comment by macearl** [comment]
Hi,

could you please post your config.

From your log i already got those information please confirm if they are coorect.

RESOLUTION=0
ASPECTRATIO=0
CATEGORY=100
TOPIC=23
SIZE=gteq
THPP=60
TIME=0
TYPE=2

I just tested the script with those settings and it seems to work fine.

**Comment by veepee78** [comment]
sure, here is full config:

#################################

### Configuration Options

#################################

# For accepted values see Section 6

MAX_RANGE=5000

# For accepted values of resolution see Section 1

RESOLUTION=0

# For accepted values of aspect ratio see Section 2

ASPECTRATIO=0

# For accepted values of category see Section 3

CATEGORY=100

# For accepted values of topic see Section 4

TOPIC=23

# For accepted values for SIZE see Section 5

SIZE=gteq

# For accepted Thumbnails per page see Section 6

THPP=60

# For download location see Section 7

LOCATION=/cygdrive/E/BackGrounds/wallbase

# Best of : see Section 8

TIME=0

# For Types see Section 9

TYPE=2

# For order Options see Section 10

ORDER=views

# See Section 11

ORDER_TYPE=desc

# See Section 12

QUERY="$1"

# See Section 14

COLLECTION=-1

# See Section 15

CATEGORIZE=1

# See Section 16

WP_RANGE_START=0
WP_RANGE_STOP=0

# See Section 17

Related=0

I use cygwin, could that have something to do with the problem? I checked
that base64 command should work on it.

VP:>

**Comment by macearl** [comment]
And your problem is that the file 0 doesnt get deleted and so the script saves the new page as 0.2 0.3...

That means the Script does download a few wallpapers from the first site?

I will try to get my hands on a windows machine to test it with cygwin.

**Comment by veepee78** [comment]
I can delete those files. If I rename them as x.jpg, they work just fine. But I assume it's not supposed to do such files? Problem is that naming.

**Comment by veepee78** [comment]
sorry, false info. pics doesn't work after renaming.

**Comment by macearl** [comment]
No the 0.2... files should be html files, you could try to open one of them in your webbrowser, then you should see one page from the toplist. the problem is in line 468. It should delete the file "0" after the script downloaded all wallpapers from that page and then download a new page and save that as "0".
But 0 doesnt get deleted in your case so it cant save a new file with the name "0" so instead it saves it as "0.2"

But you should get at least the wallpapers from the first page ( try to change the path, so that your old "downloaded.txt" wont prevent duplicates from downloading. Also you may want to lower the max range for test purposes. THPP = 20 and maxrange=60 should be good ;)

**Comment by veepee78** [comment]
yes they were html files.

I tested to blank dir, works just fine. My mistake, didn't notice new images from original location and assumed 0, 0.1 so on were the downloaded images. So stupid user only.

merry christmas!

**Comment by macearl** [comment]
So you dont get 0.1 0.2.. files in the new directory?
If so, then delete all "0" and "0.*" files from your original directory and try again.

But if you get 0.2 0.3.. files in your new directory as well, the error still occurs.

**Comment by veepee78** [comment]
Yes, creating and deleting worked fine. Didn't leave extra files. 

I tried the script on another computer, there it was unable to even create "0" file. This seems to be some sort of permissions problem. Quickly googled and found couple messages that win8 + cygwin combination might have some problems with permissions. I'd say this can be closed for now, seems the trouble source is elsewhere than in the script.
