### ISSUE TITLE
Wallbase script error file cookies not found and sed error

### ISSUE THREAD

**Issue by molwiko** [sevensins/Wallbase-Downloader#5]
I am trying to use the following script : https://github.com/sevensins/Wallbase-Downloader for wallpapers but I got the following errors : 

Cannot open cookies file ‘cookies.txt’: No such file or directory
sed: 1: "s .{29} ": unterminated substitute in regular expression
Any idea how to solve this ?

OS: MAC

http://stackoverflow.com/questions/16295620/wallbase-script-error-file-cookies-not-found-and-sed-error

**Comment by macearl** [comment]
could you post your sed version?
"man sed" in your terminal, the version should be at the bottom. If it is below 4.2.2 please update with the newest version from here: http://ftp.gnu.org/gnu/sed/ 

Then try it again, the script should work under Mac OS (you still need to change "base64 -d" to "base64 -D")
