### ISSUE TITLE
Can't seem to use AND and OR operators in the script

### ISSUE THREAD

**Issue by micah686** [sevensins/Wallbase-Downloader#7]
## Whenever I try to use operators in the configuration options in the script, it fails. Putting a single search term for query works just fine. But when I use either OR or AND and a second search term, it fails. Here is my config:

```
#################################
###   Configuration Options   ###
#################################

# For accepted values see Section 6
MAX_RANGE=240
# For accepted values of resolution see Section 1
RESOLUTION=0
# For accepted values of aspect ratio see Section 2
ASPECTRATIO=0
# For accepted values of category see Section 3
CATEGORY=100
# For accepted values of topic see Section 4
TOPIC=123
# For accepted values for SIZE see Section 5
SIZE=gteq
# For accepted Thumbnails per page see Section 6
THPP=60
# For download location see Section 7
LOCATION=~/Pictures/wallbase
# Best of : see Section 8
TIME=0
# For Types see Section 9
TYPE=4
# For order Options see Section 10
ORDER=relevance
# See Section 11
ORDER_TYPE=desc
# See Section 12
QUERY="zelda OR metroid"
# See Section 14
COLLECTION=-1
# See Section 15
CATEGORIZE=0
# See Section 16
WP_RANGE_START=0
WP_RANGE_STOP=0
# See Section 17
Related=0
```

---

And here is the output that terminal gives me:

---

```
Cannot open cookies file `cookies.txt': No such file or directory
--2013-06-27 13:35:36--  http://wallbase.cc/search/
Resolving wallbase.cc (wallbase.cc)... 46.105.105.101
Connecting to wallbase.cc (wallbase.cc)|46.105.105.101|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `index.html'

    [  <=>                                  ] 21,618      89.6K/s   in 0.2s    

2013-06-27 13:35:37 (89.6 KB/s) - `index.html' saved [21618]

Cannot open cookies file `cookies.txt': No such file or directory
--2013-06-27 13:35:37--  http://wallbase.cc/search/60
Resolving wallbase.cc (wallbase.cc)... 46.105.105.101
Connecting to wallbase.cc (wallbase.cc)|46.105.105.101|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `60'

    [  <=>                                  ] 21,626      84.5K/s   in 0.3s    

2013-06-27 13:35:39 (84.5 KB/s) - `60' saved [21626]

Cannot open cookies file `cookies.txt': No such file or directory
--2013-06-27 13:35:39--  http://wallbase.cc/search/120
Resolving wallbase.cc (wallbase.cc)... 46.105.105.101
Connecting to wallbase.cc (wallbase.cc)|46.105.105.101|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `120'

    [  <=>                                  ] 21,620      69.0K/s   in 0.3s    

2013-06-27 13:35:40 (69.0 KB/s) - `120' saved [21620]

Cannot open cookies file `cookies.txt': No such file or directory
--2013-06-27 13:35:40--  http://wallbase.cc/search/180
Resolving wallbase.cc (wallbase.cc)... 46.105.105.101
Connecting to wallbase.cc (wallbase.cc)|46.105.105.101|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `180'

    [  <=>                                  ] 21,627      98.2K/s   in 0.2s    

2013-06-27 13:35:41 (98.2 KB/s) - `180' saved [21627]

rm: cannot remove `1': No such file or directory
rm: cannot remove `cookies.txt': No such file or directory
rm: cannot remove `login': No such file or directory
rm: cannot remove `login.1': No such file or directory
```

---

When it runs, it creates a file called "data", and then a file called "120". These files are deleted when the script finishes, which is about 15 seconds after I start it. 

When I run the script with just one search term, like QUERY="zelda", I get "data", "downloaded.txt", "index.html", as well as the wallpapers. When it finishes, a wget.log is created.

So my question is, how can I make it download wallpapers with multiple queries?

**Comment by macearl** [comment]
Just had a quick look at the search options on wallbase.cc
seems like they eliminated the "and" and "or" operators

the only info i could find is that they use the sphinx search engine. But as far as i can tell in a very limited version.

according to the sphinx documentation it should be possible to use "and" and "or" as operators as well as "&" and "|" but it seems they dont work with the wallbase search.

But even the given info does not work well for me.

for example if i want to search for wallpapers that are tagged with mario but not with luigi i would (according to their  info) search like this:

```
mario not:luigi
```

But i get wallpapers with mario and luigi as tags

For now it seems that the search function does not work properly so that i cant fix it.
If you find anything else please leave a quick message so that i can change the script

**Comment by macearl** [comment]
With the newest Version at least the AND and OR Operators are working again.

Use "|" for OR and "=( ...)" for AND

for example to search for Mario AND Luigi use "=(Mario Luigi)"
to search for Mario OR Luigi use "Mario | Luigi"
