### ISSUE TITLE
Wallbase updated and script no more working

### ISSUE THREAD

**Issue by WyattLW** [sevensins/Wallbase-Downloader#8]
Is an update planned?

**Comment by macearl** [comment]
I'll look into it tonight, could you provide some details? is a single function not working, the whole script...?

**Comment by WyattLW** [comment]
It seems that the login works.. but when it goes to download wget reports
not found error.

2013/9/1 macearl notifications@github.com

**Comment by WyattLW** [comment]
--2013-09-01 14:04:03--  http://wallbase.cc/search/0/23/gteq/0/0/011/60
Risoluzione di wallbase.cc (wallbase.cc)... 37.59.24.199
Connessione a wallbase.cc (wallbase.cc)|37.59.24.199|:80... connesso.
Richiesta HTTP inviata, in attesa di risposta... 404 Not Found
2013-09-01 14:04:04 ERRORE 404: Not Found.

cat: 60: File o directory non esistente
rm: impossibile rimuovere "60": File o directory non esistente
--2013-09-01 14:04:04--  http://wallbase.cc/search/60/23/gteq/0/0/011/60
Risoluzione di wallbase.cc (wallbase.cc)... 37.59.24.199
Connessione a wallbase.cc (wallbase.cc)|37.59.24.199|:80... connesso.
Richiesta HTTP inviata, in attesa di risposta... 404 Not Found
2013-09-01 14:04:04 ERRORE 404: Not Found.

2013/9/1 Wyatt LandWalker wyattlandwalker@gmail.com

**Comment by macearl** [comment]
I just had a quick look at wallbase, i should be able to fix it today ;)

**Comment by WyattLW** [comment]
tank you! :)

2013/9/1 macearl notifications@github.com

**Comment by macearl** [comment]
just uploaded a new Version, i fixed most functions.

However i could not get the login feature to work yet. See Readme for not working Features.

If you find something else that does not work please let me know ;)

**Comment by WyattLW** [comment]
Do you now how much time would it take to fix login?
Il giorno 01/set/2013 22:11, "macearl" notifications@github.com ha
scritto:

**Comment by macearl** [comment]
Im not sure, im gonna take a look at it in the next couple of days. Right now im not sure how the csrf protection works, it looks like they just pass on 2 values (base64 encoded referer and a (maybe random) csrf value)

But if i parse them from the login page and put them in the post data it does not work.

**Comment by macearl** [comment]
Login Feature fixed ;)

**Comment by WyattLW** [comment]
<3

2013/9/2 macearl notifications@github.com
